In [2]:
import numpy as np

In [7]:
x = np.array([[10,30],
              [20,40]])

print(np.sort(x,axis= None))

[10 20 30 40]


In [10]:
data_types = [('name', 'S15'), ('class', int), ('height', float)]

student_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students = np.array(student_details, dtype= data_types)

print("original array ")
print(student_details)


print("arragnged array as height " )
print(np.sort(students,order='height'))

original array 
[('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.1), ('Pit', 5, 40.11)]
arragnged array as height 
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [12]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])


height_sorted = np.lexsort((student_id,student_height))


print(height_sorted)


for n in height_sorted:
    print(student_id[n],student_height[n])

[4 0 5 3 6 1 2]
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [19]:
x = np.random.randint(0,100,size=(5,5))

thrushold = 50

print("original random x :\n", x)


student_itmes = x[x>thrushold]

print(f'frequency that are grater the thrushold are {thrushold}',student_itmes)

original random x :
 [[18 28 99 74 51]
 [36 56 27 94 34]
 [65 70 32 24 51]
 [59  7 98 50 47]
 [ 2 65 62 67 86]]
frequency that are grater the thrushold are 50 [99 74 51 56 94 65 70 51 59 98 65 62 67 86]


In [21]:
x = np.random.randint(0,20, size=(3,3))

print(x)

[[ 9  5 12]
 [ 2  0 14]
 [18  4  5]]


In [3]:
print("date of 2017")

print(np.arange('2017-03','2017-04',dtype='datetime64[D]'))

date of 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [12]:


today = np.datetime64('today','D')

yesteterday =  today-np.timedelta64(1,'D')

tommorow = today +  np.timedelta64(1,'D')


print(yesteterday)
print(today)
print(tommorow)

2026-03-26
2026-03-27
2026-03-28


In [11]:
import numpy as np

# Get today's date with 'D' for day resolution
today = np.datetime64('today', 'D')
# Calculate yesterday's date by subtracting one day
yesterday = today - np.timedelta64(1, 'D')
# Calculate tomorrow's date by adding one day
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2026-03-26
Today: 2026-03-27
Tomorrow: 2026-03-28


Element-wise Addition with Broadcasting

In [15]:
x = np.array([[5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]])

y = np.array([1,2,3,4])

result = x-y

print(result)

[[4 4 4 4]
 [0 0 0 0]
 [8 8 8 8]]


In [16]:
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],

              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])



b = np.array([2, 3, 4, 5])



result = a*b


print(result)

[[[  2   6  12  20]
  [ 10  18  28  40]
  [ 18  30  44  60]]

 [[ 26  42  60  80]
  [ 34  54  76 100]
  [ 42  66  92 120]]]


Column-wise Division Using Broadcasting

In [25]:
import numpy as np

a = np.array([[8, 16, 24],
              [2, 4, 6],
              [12, 24, 36],
              [4, 8, 12]])


b = np.array([2, 2, 3, 4])


b_rehshape = b.reshape(4,1)

result = a/b_rehshape




print(a)
print(b)

print(result)

[[ 8 16 24]
 [ 2  4  6]
 [12 24 36]
 [ 4  8 12]]
[2 2 3 4]
[[ 4.  8. 12.]
 [ 1.  2.  3.]
 [ 4.  8. 12.]
 [ 1.  2.  3.]]


Transpose and Add 1D Array to Each Row

In [26]:
a = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15]])

b = np.array([1, 2, 3])

trasnpode_array = np.transpose(a)

result = trasnpode_array + b

print(result)

[[ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]
