In [1]:
import numpy as np

In [4]:
a = np.array([0,1,np.nan,np.inf])

print("original array")
print(a)



print("Test a given array element-wise for finiteness :")

print(np.isnan(a))




original array
[ 0.  1. nan inf]
Test a given array element-wise for finiteness :
[False False  True False]


In [9]:
arr1 = np.array([22,43,55,75,885,12,11])
arr2 = np.array([22,42,55,75,835,12,1])



print("original array:")
print(arr1)
print(arr2)


x = np.equal(arr1,arr2)
print(x)


y = np.allclose(arr1,arr2)
print(y)

original array:
[ 22  43  55  75 885  12  11]
[ 22  42  55  75 835  12   1]
[ True False  True  True False  True False]
False


In [10]:
x = np.array([1,2,3,4,5,6,7,8,9])
print("original array is :")

print(x)

print("size and memory occupation will be :")
print(x.size *x.itemsize)

original array is :
[1 2 3 4 5 6 7 8 9]
size and memory occupation will be :
72


CREATING ARRRAY FROM 30 TO 70

In [11]:
arr = np.arange(30,70)
print("range of the array will  be :")

print(arr)

range of the array will  be :
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Create Array of Even Integers 30 to 70

In [18]:
x = np.arange(30,70,2)
print(x)





[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Create 3x3 Identity Matrix

In [ ]:
arr_2d = np.identity(3)
print(arr_2d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Generate Random Number [0,1]


In [24]:
x = np.random.normal(1,10)
print(x)

-8.058876326992912


Generate Random Array from Standard Normal

In [25]:
x = np.random.normal(0,1,15)

print(x)

[-1.46216027  1.48152921  0.10435147  1.90631623  0.68145474 -0.13058865
 -1.38045711 -1.03665106  1.22079404  0.03168117  0.09488438 -0.26320951
  2.11855992  0.79426257  0.98300626]




Vector 15-55 Without First/Last Values

In [28]:
arr = np.arange(15,55)

print("print original :")
print(arr)

print(arr[1:-1])



print original :
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Create and Iterate 3x4 Array

In [ ]:
x = np.identity(3)
print(x)


TypeError: Cannot interpret '4' as a data type

In [5]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing integers from 0 to 20 using np.arange()
x = np.arange(21)

# Printing a message indicating the original vector 'x'
print("Original vector:")
print(x)

# Printing a message indicating changing the sign of numbers in the range from 9 to 15
# Using boolean indexing, multiplying elements between 9 and 15 by -1 to change their sign
x[(x >= 9) & (x <= 15)] *= -1

# Printing the modified vector 'x'
print("After changing the sign of the numbers in the range from 9 to 15:")
print(x) 


Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [9]:
x = np.random.randint(1,20,7)
print(x)

[16  1 17  1  8 17  5]


MULTIPLICATON OF TWO NUMBERS

In [10]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([1,2,3,4,5])


new_multiplication = x1*x2

print(new_multiplication)

[ 1  4  9 16 25]


Create 3x4 Matrix (10 to 21)


In [15]:
arr = np.arange(10,22).reshape((3,4))

print(arr)

print("number and columns of the matrix",arr.shape)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
number and columns of the matrix (3, 4)


In [16]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Printing the version of NumPy installed
print(np.__version__)


2.4.3


In [17]:

l = [12.23, 13.32, 100, 36.32]

print("original array")


a = np.array(l)


print(a)

original array
[ 12.23  13.32 100.    36.32]


In [19]:
arr_ones = np.ones((3,3,2))
print(arr_ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:
arr_zeroes = np.zeros(10)
print(arr_zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
x = np.array([[1,2,3],[2,3,4]])

print(x)

[[1 2 3]
 [2 3 4]]


In [26]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


reverse the array

In [28]:
x = np.arange(10,20)
print(x)

reverse_array =x[::-1]
print(reverse_array)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


In [35]:
x = np.array[1,2,3,4,5]

repeat_array = np.tile(x,2)

print(repeat_array)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [36]:
import pandas as pd
import matplotlib.pyplot as plt
iris = pd.read_csv("iris.csv")
iris.describe().plot(kind = "area",fontsize=16, figsize = (15,8), table = True, colormap="Accent")
plt.xlabel('Statistics',)
plt.ylabel('Value')
plt.title("General Statistics of Iris Dataset")
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [9]:
arr1 = np.array([1,2,3,4,5])

arr2 = np.array([1,2,3,6,7])
result = np.array_equal(arr1,arr2)


print(result)

False


INTERSECTED ARRAY

In [10]:
arr1 = np.array([1,2,3,4,5,6])

print("array one is :", arr1)


arr2 = np.array([2,3,4,5,8,1])

print("array two is :",arr2)


intersected_arrya = np.intersect1d(arr1,arr2)

print(intersected_arrya)

array one is : [1 2 3 4 5 6]
array two is : [2 3 4 5 8 1]
[1 2 3 4 5]


In [11]:



arr1 = np.array([1,2,3,4,5,6])

print("array one is :", arr1)


arr2 = np.array([2,3,4,5,8,1])

print("array two is :",arr2)


intersected_arrya = np.setxor1d(arr1,arr2)

print(intersected_arrya)



array one is : [1 2 3 4 5 6]
array two is : [2 3 4 5 8 1]
[6 8]


CHECK ALL THE ELEMENT ARE TRUE AND FALSE

In [13]:
x = np.all([[True,False],[True,True]])

y = np.all([[True,True],[True,True]])


print(x,y)


x1 = np.all([1,2,0,-7])

x2 = np.all([1,2,-7])

print(x1,x2)


False True
False True


In [16]:
x1 = np.array([10,30])

x2 = np.array([20,60])

result = np.mean(np.concatenate([x1, x2]))

print(result)

30.0


In [24]:
p = [[1,0],[1,2]]



print("original array ")
print(p)




result = np.linalg.det(p)

print(result)

original array 
[[1, 0], [1, 2]]
2.0


In [31]:
x = np.random.normal(size =4)
print(x)

[-0.40237683 -0.30885751  0.0457948  -0.46408445]


In [38]:
x = np.random.random((5, 4, 5))
print(x)


[[[0.62259327 0.4850114  0.84177194 0.62238667 0.72980515]
  [0.88590787 0.5758322  0.37056752 0.62414962 0.85020207]
  [0.29811675 0.64444426 0.43744112 0.20893129 0.60077475]
  [0.51342762 0.99672397 0.33291587 0.47427281 0.5159624 ]]

 [[0.26852742 0.74851566 0.48722466 0.61007027 0.00978325]
  [0.38078518 0.21159556 0.35600599 0.03002447 0.37587307]
  [0.73873898 0.99942378 0.3548306  0.09474933 0.72877049]
  [0.29902185 0.03158218 0.3795081  0.32658599 0.32005502]]

 [[0.41378307 0.10248334 0.17819568 0.25086582 0.49315189]
  [0.56819805 0.40547078 0.97958818 0.38408109 0.37018975]
  [0.22074941 0.32415367 0.99866215 0.83107555 0.70752217]
  [0.92795086 0.93265866 0.51940362 0.4819612  0.82654752]]

 [[0.75672018 0.71347757 0.91104973 0.45697268 0.55290294]
  [0.01027465 0.85632891 0.10715859 0.07032314 0.05385981]
  [0.14038231 0.55606743 0.47249524 0.77947341 0.40829495]
  [0.89975061 0.10518504 0.01901283 0.70529334 0.49677358]]

 [[0.32470697 0.49947501 0.49114065 0.32167291 0

In [53]:
#Source: https://bit.ly/2MjeQ6z
import requests
APPID = "**************************"  # <-- Put your OpenWeatherMap appid here!
URL_BASE = "http://api.openweathermap.org/data/2.5/"
def current_weather(q: str = "", appid: str = APPID) -> dict:
    """https://openweathermap.org/api"""
    return requests.get(URL_BASE + "weather", params=locals()).json()
def weather_forecast(q: str = "", appid: str = APPID) -> dict:
    """https://openweathermap.org/forecast5"""
    return requests.get(URL_BASE + "forecast", params=locals()).json()
def weather_onecall(lat: float = 55.68, lon: float = 12.57, appid: str = APPID) -> dict:
    """https://openweathermap.org/api/one-call-api"""
    return requests.get(URL_BASE + "onecall", params=locals()).json()
if __name__ == "__main__":
    from pprint import pprint
    while True:
        location = input("Input a location: ").strip()
        if location:
            pprint(current_weather(location))
        else:
            break


ModuleNotFoundError: No module named 'requests'