In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr[2:7])
print(arr[3:12:2])

[3 4 5 6 7]
[ 4  6  8 10 12]


In [ ]:
add_2 = np.array([[1,2],[3,4],[5,6],[2,3]])


print(np.sort(add_2,axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
##filter numbers

number =np.array([1,2,3,4,5,6,7,8,9,10])

even_number = number[number %2 ==0]
print(even_number)






[ 2  4  6  8 10]


In [ ]:
## filter with mask
indices = [1,3,5]
print(number[indices])


where_result = np.where(number >5)
print("NP WHERE ", number[where_result])




[2 4 6]


IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
condition_array = np.where(number>5, "true", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'true' 'true' 'true' 'true'
 'true']


ADDING AND REMOVING DATA


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate(arr1+arr2)

print(combined)

ValueError: zero-dimensional arrays cannot be concatenated

array compacabality

if (number>5){
    number  *4
}


else{
    number
}

In [3]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5]
