In [1]:
import numpy as np

In [4]:
a = np.array([0,1,np.nan,np.inf])

print("original array")
print(a)



print("Test a given array element-wise for finiteness :")

print(np.isnan(a))




original array
[ 0.  1. nan inf]
Test a given array element-wise for finiteness :
[False False  True False]


In [9]:
arr1 = np.array([22,43,55,75,885,12,11])
arr2 = np.array([22,42,55,75,835,12,1])



print("original array:")
print(arr1)
print(arr2)


x = np.equal(arr1,arr2)
print(x)


y = np.allclose(arr1,arr2)
print(y)

original array:
[ 22  43  55  75 885  12  11]
[ 22  42  55  75 835  12   1]
[ True False  True  True False  True False]
False


In [10]:
x = np.array([1,2,3,4,5,6,7,8,9])
print("original array is :")

print(x)

print("size and memory occupation will be :")
print(x.size *x.itemsize)

original array is :
[1 2 3 4 5 6 7 8 9]
size and memory occupation will be :
72


CREATING ARRRAY FROM 30 TO 70

In [11]:
arr = np.arange(30,70)
print("range of the array will  be :")

print(arr)

range of the array will  be :
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Create Array of Even Integers 30 to 70

In [18]:
x = np.arange(30,70,2)
print(x)





[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Create 3x3 Identity Matrix

In [ ]:
arr_2d = np.identity(3)
print(arr_2d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Generate Random Number [0,1]


In [24]:
x = np.random.normal(1,10)
print(x)

-8.058876326992912


Generate Random Array from Standard Normal

In [25]:
x = np.random.normal(0,1,15)

print(x)

[-1.46216027  1.48152921  0.10435147  1.90631623  0.68145474 -0.13058865
 -1.38045711 -1.03665106  1.22079404  0.03168117  0.09488438 -0.26320951
  2.11855992  0.79426257  0.98300626]




Vector 15-55 Without First/Last Values

In [28]:
arr = np.arange(15,55)

print("print original :")
print(arr)

print(arr[1:-1])



print original :
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]
