In [1]:
import numpy as np

add_1 = ([1,2,3,5,6])
print(add_1)



add_2 = np.array([[1,2,3],[4,5,6]])
print(add_2)

[1, 2, 3, 5, 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
zeros = np.zeros((3,3))
print(zeros)


ones = np.ones((3,4))
print(ones)


full = np.full((2,2),6)
print(full)



random = np.random.random((2,3))
print(random)


sequence = np.arange(0,10,2)
print(sequence)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6]
 [6 6]]
[[0.46162723 0.67575667 0.95697028]
 [0.95436908 0.6765282  0.42428653]]
[0 2 4 6 8]


In [8]:
arr = np.array([[1,2,3],
               [5,4,6]])


print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64
